### ISSUE TITLE
Add bilingual fields to Vocabulary

### ISSUE THREAD

**Issue by steveoni** [FCSCOpendata/ckanext-vocabulary#1]
we want to enable input fields to add translated versions of vocabulary and tags.

## Acceptance

- [ ] Have input field for the Arabic version of the vocabulary
- [ ] Have input fields for Arabic version of corresponding tags

## Task
- [x] add Arabic field to vocabulary create page
- [x] update vocabulary controller to save additional translated field
- [x] add function to create as many tags as possible
- [x] update controller to update tag creation
